builders:
  computer_launch:
    import: "package:computer_generator/computer_generator.dart"
    builder_factories: ["isolateSideLaunchableGenerator"]
    build_extensions: { ".dart": ["launchable.g.dart"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
