name: computer
version: 1.0.2
author: Sergei Lavinov <lsa@91.team>
description: Easy to use pool of concurrent workers with compute() like API.
homepage: https://github.com/91team/computer
environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  meta: ^1.1.7

dev_dependencies:
  test: ^1.14.6
  pedantic: ^1.9.2
